name: Build Docker images
 
on:
  push:
    branches: ["main"]
 
jobs:
  build-and-push-dockerfile-image:
    name: Deploy app
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Make sure to add the secrets in your repository in -> Settings -> Secrets (Actions) -> New repository secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Make sure to add the secrets in your repository in -> Settings -> Secrets (Actions) -> New repository secret
 
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Make sure to replace with your own namespace and repository
          tags: |
            hsharda039/revitin-rmw:latest
          platforms: linux/amd64

      - name: Dokploy Deployment
        uses: benbristow/dokploy-deploy-action@0.0.1
        with:
          auth_token: ${{ secrets.DOKPLOY_TOKEN }}
          application_id: aY1-4R3Qwq4M63UaaFH0H
          dokploy_url: ${{ secrets.DOKPLOY_URL }}
